version: '3'
services:
  phpipam:
    image: "cent7-phpipam:1.3.2"
    restart: always
    container_name: phpipam
    hostname: phpipam
    domainname: prosethsolutions.lab 
    network_mode: bridge
    ports:
      - 80:80
    volumes:
      - /srv/docker-data/phpipam:/var/www/html
